POST https://api.vk.com/method/messages.send?group_id=187421915&access_token=dc2665238b736d270d6314240e62affceca6e8560c16d8f661cba5c58d83e030ff54a20236240141bf3e0&user_id=493384597&message=Песос&v=5.102&random_id=563457879990&keyboard={ "one_time": false, "buttons": [ [ { "action": { "type": "text", "label": "Аналитик", "payload": "{\"button\": \"1\"}" }, "color": "primary" }, { "action": { "type": "text", "label": "Разработчик", "payload": "{\"button\": \"2\"}" }, "color": "primary" } ], [ { "action": { "type": "text", "label": "Тестировщик", "payload": "{\"button\": \"3\"}" }, "color": "primary" }, { "action": { "type": "text", "label": "Менеджер проектов", "payload": "{\"button\": \"4\"}" }, "color": "primary" } ], [ { "action": { "type": "text", "label": "Сформировать команду", "payload": "{\"button\": \"5\"}" }, "color": "positive" } ] ] }

###

GET https://api.vk.com/method/messages.send?access_token=dc2665238b736d270d6314240e62affceca6e8560c16d8f661cba5c58d83e030ff54a20236240141bf3e0&v=5.102&user_id=493384597&random_id=6334924724549167320&message=Привет! Данный бот поможет тебе найти нужных специалистов для реализации твоей бизнес идеи! В случае, если идея будет доработана до минимально жизнеспособного продукта (MVP), у тебя появится возможность получить свои первые инвестиции на развитие проекта! Удачи!&keyboard={ "one_time": false, "buttons": [ [ { "action": { "type": "text", "label": "Предложить идею", "payload": "{\"button\": \"1\"}" }, "color": "positive" }, { "action": { "type": "text", "label": "Добавить участника", "payload": "{\"button\": \"2\"}" }, "color": "primary" } ] ]}&group_id=187421915

###
